"""
Reading run records (Stage 1 T4): list, show, compare, and the two generated files Claude reads instead of Joe
measuring and reporting, sim/runs/DIGEST.md (latest run per scenario) and sim/runs/ENVELOPE.md (worst case per joint).

    fy runs list [--scenario S]
    fy runs show <id>
    fy runs compare <idA> <idB>
    fy runs digest
    fy runs envelope

Both generated files are deterministic: sorted, fixed number formats, no timestamps other than run ids, and a hard
line cap that does not depend on how many historical runs exist (only the latest and the previous run of a scenario
are read). The input order does not matter.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import runrecord

REPO = Path(__file__).resolve().parents[2]
META_FILE = REPO / "params" / "snapshot.meta.json"
GENERATED = "GENERATED by sim/scripts/runs_report.py from sim/runs/*/summary.json. Do not edit; rerun `fy runs {name}`."
MAX_LINES = 399  # the brief's cap is "under 400 lines"
NOT_INCLUDED = ("gait", "stairs", "sit-to-stand")

JOINT_METRICS = ("torque_peak_nm", "torque_rms_nm", "speed_peak_rad_s", "power_peak_w")
INPUT_ENV = ("mujoco", "python", "numpy")


# ------------------------------------------------------------------------------ small helpers

def _f(x, nd) -> str:
    return "-" if x is None else f"{x:.{nd}f}"


def _signed(x, nd) -> str:
    return f"{x:+.{nd}f}"


def _pct(old, new) -> str:
    """Percent change as '+20.0%'; '=' when nothing changed; 'n/a' from zero."""
    if abs(new - old) < 1e-12:
        return "="
    if old == 0:
        return "n/a"
    return f"{(new - old) / abs(old) * 100:+.1f}%"


def _rom(pair) -> str:
    return "-" if pair is None else f"{pair[0]:.1f}..{pair[1]:.1f}"


def _short(sha, n=12) -> str:
    return "-" if not sha else sha[:n]


def _latest_by_scenario(summaries) -> dict:
    """{scenario: [runs, oldest first]}"""
    out = {}
    for s in sorted(summaries, key=lambda r: r["run_id"]):
        out.setdefault(s["scenario"]["name"], []).append(s)
    return out


def _cap(lines: list) -> str:
    if len(lines) > MAX_LINES:
        lines = lines[:MAX_LINES - 1] + [f"(truncated at {MAX_LINES} lines)"]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------------------ comparing

def differing_inputs(a: dict, b: dict) -> dict:
    """{input name: (value in a, value in b)} for exactly the inputs that differ."""
    out = {}

    def note(name, x, y):
        if x != y:
            out[name] = (x, y)
    note("commit", a["git_commit"], b["git_commit"])
    note("working tree", (a["git_dirty"], a["diff_sha256"]), (b["git_dirty"], b["diff_sha256"]))
    note("snapshot", a["snapshot_sha256"], b["snapshot_sha256"])
    note("model", a["model_sha256"], b["model_sha256"])
    note("scenario parameters", a["scenario"]["params"], b["scenario"]["params"])
    note("controller", a["controller"], b["controller"])
    note("seed", a["seed"], b["seed"])
    for key in INPUT_ENV:
        note(f"env.{key}", a["env"][key], b["env"][key])
    return out


def _describe(name, pair) -> str:
    x, y = pair
    if name in ("commit", "snapshot", "model"):
        return f"{name}: {_short(x, 12)} -> {_short(y, 12)}"
    if name == "working tree":
        word = lambda v: "dirty " + _short(v[1], 8) if v[0] else "clean"  # noqa: E731
        return f"{name}: {word(x)} -> {word(y)}"
    if name == "scenario parameters":
        a, b = json.dumps(x, sort_keys=True), json.dumps(y, sort_keys=True)
        keys = sorted(k for k in set(x) | set(y) if x.get(k) != y.get(k))
        return f"{name}: {', '.join(keys)} differ"
    return f"{name}: {x} -> {y}"


def _git_show(repo, commit, path) -> str | None:
    try:
        return subprocess.run(["git", "show", f"{commit}:{path}"], cwd=repo, check=True, capture_output=True).stdout.decode("utf-8")
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return None


def _snapshot_rows(text) -> dict:
    rows = {}
    for line in text.splitlines()[1:]:
        key, _, rest = line.partition(",")
        rows[key] = rest.split(",")[0] if rest else ""
    return rows


def _attribute(a, b, repo) -> list:
    """Lines saying which snapshot rows changed between the two commits, or why that cannot be said."""
    if a["snapshot_sha256"] == b["snapshot_sha256"]:
        return ["Snapshot unchanged."]
    if a["git_dirty"] or b["git_dirty"]:
        return ["Snapshot changed but a run had a dirty tree, so cannot attribute the change to snapshot rows."]
    ta = _git_show(repo or REPO, a["git_commit"], "params/snapshot.csv")
    tb = _git_show(repo or REPO, b["git_commit"], "params/snapshot.csv")
    if ta is None or tb is None:
        return ["Snapshot changed but a commit is not available here, so cannot attribute the change to snapshot rows."]
    ra, rb = _snapshot_rows(ta), _snapshot_rows(tb)
    changed = [f"  {k}: {ra.get(k, '(absent)')} -> {rb.get(k, '(absent)')}" for k in sorted(set(ra) | set(rb)) if ra.get(k) != rb.get(k)]
    return ["Changed snapshot rows (git show <commit>:params/snapshot.csv):"] + (changed or ["  (none: the files differ only in formatting)"])


def compare(a: dict, b: dict, repo=None) -> str:
    lines = [f"compare {a['run_id']} -> {b['run_id']}", ""]
    diff = differing_inputs(a, b)
    lines.append("Inputs that differ:" if diff else "Inputs that differ: none")
    lines += [f"  {_describe(k, diff[k])}" for k in sorted(diff)]
    if "snapshot" in diff or "commit" in diff:
        lines += [""] + _attribute(a, b, repo)
    lines += ["", "Results:"]
    if a["outcome"] != b["outcome"]:
        lines.append(f"  outcome: {a['outcome']} -> {b['outcome']}")
    unchanged = 0

    def delta(label, x, y, nd=3):
        nonlocal unchanged
        if x is None or y is None or abs(y - x) < 1e-12:
            unchanged += 1
            return
        lines.append(f"  {label}: {x:.{nd}f} -> {y:.{nd}f} ({_signed(y - x, nd)}, {_pct(x, y)})")
    for name in sorted(set(a["joints"]) & set(b["joints"])):
        for key in JOINT_METRICS:
            delta(f"{name} {key}", a["joints"][name][key], b["joints"][name][key])
    for side, other in ((a, b), (b, a)):
        only = sorted(set(side["joints"]) - set(other["joints"]))
        if only:
            lines.append(f"  joints only in {side['run_id']}: {', '.join(only)}")
    for foot in sorted(set(a["contacts"]) & set(b["contacts"])):
        for key in ("normal_force_peak_n", "friction_ratio_peak"):
            delta(f"{foot} {key}", a["contacts"][foot][key], b["contacts"][foot][key])
    delta("support_margin_min_m", a["balance"]["support_margin_min_m"], b["balance"]["support_margin_min_m"], 6)
    da, db = a.get("diagnostics", {}), b.get("diagnostics", {})
    for key in sorted(set(da) & set(db)):
        delta(f"diagnostics {key}", da[key], db[key], 6)
    lines.append(f"  {unchanged} metrics unchanged")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------------------ show and list

def list_runs(summaries, scenario=None) -> str:
    rows = []
    for s in sorted(summaries, key=lambda r: r["run_id"]):
        if scenario and s["scenario"]["name"] != scenario:
            continue
        rows.append(f"{s['run_id']}  {s['outcome']:9} {s['scenario']['name']}  {s['git_commit'][:7]}"
                    f"{'+dirty' if s['git_dirty'] else ''}  snapshot {_short(s['snapshot_sha256'])}")
    return "\n".join(rows) + ("\n" if rows else "")


def _joint_table(joints, previous=None) -> list:
    head = "| joint | peak torque Nm | rms torque Nm | peak speed rad/s | peak power W | ROM used deg | limit deg | limit hit |"
    lines = [head + (" d peak torque |" if previous is not None else ""), "|" + "---|" * (head.count("|") - 1 + (previous is not None))]
    for name in sorted(joints):
        j = joints[name]
        row = (f"| {name} | {_f(j['torque_peak_nm'], 2)} | {_f(j['torque_rms_nm'], 2)} | {_f(j['speed_peak_rad_s'], 3)} | "
               f"{_f(j['power_peak_w'], 2)} | {_rom(j['rom_used_deg'])} | {_rom(j['rom_limit_deg'])} | {_f(j['limit_hit_fraction'], 3)} |")
        if previous is not None:
            old = previous.get(name)
            row += f" {_pct(old['torque_peak_nm'], j['torque_peak_nm']) if old else '-'} |"
        lines.append(row)
    return lines


def _contacts_lines(s) -> list:
    lines = []
    for foot in sorted(s["contacts"]):
        c = s["contacts"][foot]
        lines.append(f"Contact {foot}: peak normal force {_f(c['normal_force_peak_n'], 1)} N, peak friction ratio {_f(c['friction_ratio_peak'], 3)}")
    margin = s["balance"]["support_margin_min_m"]
    lines.append("Balance: support margin min " + ("n/a (not measured)" if margin is None else f"{margin:.4f} m"))
    return lines


def _checks_line(s) -> str:
    c = s["checks"]
    return (f"Checks at run start: passed {', '.join(c['passed']) or 'none'}; failed {', '.join(c['failed']) or 'none'}; "
            f"waived {', '.join(c['waived']) or 'none'}; status {'STALE (computed for another model)' if c['status_stale'] else 'current'}")


def show(s: dict) -> str:
    lines = [f"{s['run_id']}  {s['outcome']}", "",
             f"scenario {s['scenario']['name']}, support {s['support']}, seed {s['seed']}, controller {s['controller']['name'] or '-'} {s['controller']['version']}",
             f"commit {s['git_commit']}{' (dirty, diff ' + _short(s['diff_sha256'], 12) + ')' if s['git_dirty'] else ''}",
             f"snapshot {_short(s['snapshot_sha256'])}, model {_short(s['model_sha256'])}",
             f"timestep {s['timestep_s']} s, duration {s['duration_s']:.4f} s, window {s['window']['start_s']}..{s['window']['end_s']} s",
             f"env mujoco {s['env']['mujoco']}, python {s['env']['python']}, numpy {s['env']['numpy']}", ""]
    lines += _joint_table(s["joints"]) if s["joints"] else ["(no joints measured)"]
    if s.get("skipped"):
        lines.append("Skipped: " + ", ".join(f"{k} ({v})" for k, v in sorted(s["skipped"].items())))
    lines += [""] + _contacts_lines(s)
    lines += [f"Diagnostic {k}: {v}" for k, v in sorted(s.get("diagnostics", {}).items())]
    lines += ["", _checks_line(s)]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------------------ digest

def digest(summaries, current_model_sha=None) -> str:
    lines = [f"<!-- {GENERATED.format(name='digest')} -->", "", "# Run digest", ""]
    groups = _latest_by_scenario(summaries)
    if not groups:
        return _cap(lines + ["No runs recorded yet."])
    lines += ["Latest run of each scenario, with the change against the run before it. Joint torque is about the model's own hinge axes.", ""]
    for name in sorted(groups):
        runs = groups[name]
        s, prev = runs[-1], (runs[-2] if len(runs) > 1 else None)
        stale = current_model_sha is not None and s["model_sha256"] != current_model_sha
        lines += [f"## {name}", "",
                  f"Latest: {s['run_id']}, {s['outcome']}, {s['support']}, commit {s['git_commit'][:7]}{'+dirty' if s['git_dirty'] else ''}, "
                  f"snapshot {_short(s['snapshot_sha256'])}, model {_short(s['model_sha256'])}"
                  f"{'  STALE: the committed model has changed since this run' if stale else ''}",
                  f"Window {s['window']['start_s']}..{s['window']['end_s']} s, duration {s['duration_s']:.3f} s, timestep {s['timestep_s']} s, runs recorded {len(runs)}"]
        if prev is None:
            lines.append("Previous run: none.")
        else:
            diff = differing_inputs(prev, s)
            lines.append(f"Previous run: {prev['run_id']}, {prev['outcome']}; inputs that differ: "
                         + (", ".join(sorted(diff)) if diff else "none"))
        lines.append("")
        if s["joints"]:
            lines += _joint_table(s["joints"], prev["joints"] if prev else {})
        elif s["outcome"] != "completed":
            lines.append(f"No joints measured: the run ended ({s['outcome']}) before its measurement window.")
        else:
            lines.append("No joints measured.")
        if s.get("skipped"):
            lines.append("")
            lines.append("Skipped: " + ", ".join(f"{k} ({v})" for k, v in sorted(s["skipped"].items())))
        lines += [""] + _contacts_lines(s)
        pose = s["scenario"]["params"].get("pose")
        diag = s.get("diagnostics", {})
        if pose and "lean_angle_deg" in diag:
            lines.append("Pose: " + ", ".join(f"{k} {v}" for k, v in sorted(pose.items())) + f"; lean angle {diag['lean_angle_deg']:.3f} deg"
                         + (f"; window-mean CoM offset {diag['com_offset_window_mean_m'] * 1000:.1f} mm; sag {diag['com_sag_m'] * 1000:.1f} mm"
                            if "com_sag_m" in diag else "; no CoM offset measured (the run ended before its window)"))
        lines += [f"- {k}: {v:.6g}" if isinstance(v, float) else f"- {k}: {v}" for k, v in sorted(s.get("diagnostics", {}).items())]
        lines += ["", _checks_line(s), ""]
    return _cap(lines)


# ------------------------------------------------------------------------------ envelope

def envelope(summaries, current_model_sha=None) -> str:
    lines = [f"<!-- {GENERATED.format(name='envelope')} -->", "", "# Load envelope", ""]
    groups = _latest_by_scenario(summaries)
    if not groups:
        return _cap(lines + ["No runs recorded yet."])
    included, excluded = {}, []
    for name in sorted(groups):
        s = groups[name][-1]
        if current_model_sha is not None and s["model_sha256"] != current_model_sha:
            excluded.append(f"{s['run_id']} ({name}): stale, recorded for another model")
        elif s["outcome"] != "completed":
            excluded.append(f"{s['run_id']} ({name}): {s['outcome']}, so its numbers do not count")
        else:
            included[name] = s
    lines += [
        "Worst case per joint across the latest run of every scenario, with the run that drives it. Joint torque is about the model's own "
        "hinge axes (the decoupled hip architecture), not actuator torque.",
        "",
        "Scenario classes included: " + (", ".join(f"{n} ({included[n]['run_id']})" for n in sorted(included)) or "none") + ".",
        "Not yet included: " + ", ".join(NOT_INCLUDED) + " (they need reference kinematics with citable provenance, Stage 2).",
        "This is not a complete sizing basis: do not size an actuator from it.",
    ]
    if excluded:
        lines += ["Excluded latest runs: " + "; ".join(excluded) + "."]
    lines.append("")

    best, rom, limits, no_rom = {}, {}, {}, set()
    for name in sorted(included):
        s = included[name]
        no_rom |= set(s.get("skipped", {}))
        for jn, j in s["joints"].items():
            if j["rom_limit_deg"] is None:
                no_rom.add(jn)
            else:
                limits.setdefault(jn, j["rom_limit_deg"])
            lo, hi = j["rom_used_deg"]
            cur = rom.setdefault(jn, [lo, hi])
            cur[0], cur[1] = min(cur[0], lo), max(cur[1], hi)
            for key in JOINT_METRICS:
                cand = (j[key], s["run_id"])
                have = best.setdefault(jn, {}).get(key)
                # larger value wins; on a tie the smaller run id
                if have is None or cand[0] > have[0] or (cand[0] == have[0] and cand[1] < have[1]):
                    best[jn][key] = cand
    names = sorted(set(best) | no_rom)
    lines += ["| joint | peak torque Nm | driving run | peak speed rad/s | driving run | peak power W | driving run | ROM used deg | limit deg |",
              "|" + "---|" * 9]
    for jn in names:
        if jn not in best:
            lines.append(f"| {jn} | no data | - | no data | - | no data | - | - | unlimited |")
            continue
        b = best[jn]
        lines.append(f"| {jn} | {b['torque_peak_nm'][0]:.2f} | {b['torque_peak_nm'][1]} | {b['speed_peak_rad_s'][0]:.3f} | {b['speed_peak_rad_s'][1]} | "
                     f"{b['power_peak_w'][0]:.2f} | {b['power_peak_w'][1]} | {_rom(rom[jn])} | {_rom(limits.get(jn)) if jn in limits else 'unlimited'} |")
    lines.append("")
    if no_rom:
        lines.append("Joints with no ROM data (unlimited, so never swept; each row reflects the standing hold only, or no data): "
                     + ", ".join(sorted(no_rom)) + ".")
    else:
        lines.append("Joints with no ROM data: none.")
    return _cap(lines)


# ------------------------------------------------------------------------------ command line

def _find(summaries, ident):
    wanted = ident if ident.startswith("run.") else f"run.{ident}"
    for s in summaries:
        if s["run_id"] == wanted:
            return s
    raise KeyError(f"no run {ident}")


def _current_model_sha(meta_path):
    try:
        return json.loads(Path(meta_path).read_text(encoding="utf-8")).get("model_sha256")
    except (OSError, ValueError):
        return None


def main(argv=None) -> int:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--runs-dir", help=argparse.SUPPRESS)
    common.add_argument("--meta", help=argparse.SUPPRESS)
    common.add_argument("--repo", help=argparse.SUPPRESS)
    ap = argparse.ArgumentParser(prog="fy runs", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="command", required=True)
    p = sub.add_parser("list", parents=[common], help="list runs")
    p.add_argument("--scenario")
    sub.add_parser("show", parents=[common], help="show one run").add_argument("run")
    p = sub.add_parser("compare", parents=[common], help="compare two runs")
    p.add_argument("a")
    p.add_argument("b")
    sub.add_parser("digest", parents=[common], help="write sim/runs/DIGEST.md")
    sub.add_parser("envelope", parents=[common], help="write sim/runs/ENVELOPE.md")
    args = ap.parse_args(argv)

    runs_dir = Path(args.runs_dir or runrecord.RUNS_DIR)
    summaries = runrecord.load_summaries(runs_dir)
    try:
        if args.command == "list":
            sys.stdout.write(list_runs(summaries, args.scenario))
        elif args.command == "show":
            sys.stdout.write(show(_find(summaries, args.run)))
        elif args.command == "compare":
            sys.stdout.write(compare(_find(summaries, args.a), _find(summaries, args.b), repo=args.repo))
        else:
            sha = _current_model_sha(args.meta or META_FILE)
            text, name = (digest(summaries, sha), "DIGEST.md") if args.command == "digest" else (envelope(summaries, sha), "ENVELOPE.md")
            path = runs_dir / name
            runs_dir.mkdir(parents=True, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
            print(f"wrote {path} ({len(text.splitlines())} lines)")
    except KeyError as e:
        print(f"runs: {e.args[0]}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
